<a style="text-decoration: none;" href="<?= $block->escapeUrl($block->getNewTicketFormLink()); ?>">
    <button type="button" title="Submit New Ticket" class="primary">
        <span><?= __('Submit New Ticket') ?></span>
    </button>
</a>

<?php if($block->hasTickets()): ?>
<table>

    <thead>
        <tr>
            <th><?= __('Subject') ?></th>
            <th><?= __('Status') ?></th>
            <th><?= __('Created at') ?></th>
        </tr>
    </thead>

    <tbody>
    <?php foreach($block->ticketList() as $ticket): ?>

            <tr>
                <td><a href="<?= $block->escapeUrl($block->getUrl($block->getTicketUrl(), ['ticket_id' => $ticket['ticket_id']])) ?>"><?= $block->escapeHtml($ticket['ticket_subject']) ?></a></td>
                <td><?= $block->escapeHtml(ucfirst($block->getTicketStatusArray()[$ticket['ticket_status']])) ?></td>
                <td><?= $block->formatDate($ticket['created_at'], 3, true) ?></td>
            </tr>

    <?php endforeach; ?>
    </tbody>

</table>
<?php else: ?>
    <h3><?= __('You do not have any submitted tickets'); ?></h3>
<?php endif; ?>
